sudo: false

language: python

python: 2.7

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/war

script:
  - ./setup.sh
  - ./run_tests.py

notifications:
  email:
    - dev-automation@lists.mozilla.org
  irc:
    - "irc.mozilla.org#automation"
